"""init tables

Revision ID: db86ee148162
Revises:
Create Date: 2025-12-25 15:43:02.714425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PgEnum

# revision identifiers, used by Alembic.
revision: str = 'db86ee148162'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DB_SCHEMA = "repos"

status_enum = PgEnum(
    'queued', 'processing', 'done', 'failed',
    name='repo_index_status',
    schema=DB_SCHEMA,
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text(f'CREATE SCHEMA IF NOT EXISTS "{DB_SCHEMA}"'))

    # enum for indexing status
    op.execute(sa.text(f"""
    DO $$
    BEGIN
        CREATE TYPE "{DB_SCHEMA}".repo_index_status AS ENUM ('queued','processing','done','failed');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """))

    op.create_table('repo_index_states',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('qdrant_collection', sa.Text(), nullable=False),
    sa.Column('status', status_enum, nullable=False, server_default='queued'),
    sa.Column('vectors_upserted', sa.Integer(), nullable=False, server_default="0"),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repository_id', name='uq_repo_index_state'),
    schema=DB_SCHEMA
    )

    op.create_table('repositories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.Text(), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    schema=DB_SCHEMA
    )

    op.create_index("ix_repo_index_states_status", "repo_index_states", ["status"], schema=DB_SCHEMA)
    op.create_index("ix_repo_index_states_repo", "repo_index_states", ["repository_id"], schema=DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repositories', schema=DB_SCHEMA)
    op.drop_table('repo_index_states', schema=DB_SCHEMA)
    op.execute(f'DROP TYPE IF EXISTS {DB_SCHEMA}.repo_index_status')
    # ### end Alembic commands ###
