version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # optional UI/metrics
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__STORAGE_TYPE=rocksdb
